### ISSUE TITLE
Producer example in README.md deprecated & cannot get to work

### ISSUE THREAD

**Issue by aliekens** [joekiller/jruby-kafka#25]
Hi,

I'm just starting out experimenting with `jruby-kafka`. Upon trying the examples in the README, I learned that they are no longer current. As a first step, I assume that the producer example in the README should be changed to:

```ruby
require 'jruby-kafka'

producer_options = {:broker_list => "localhost:9092"}

producer = Kafka::Producer.new(producer_options)
producer.connect()
producer.send_msg('test', nil, 'test message')
```

The main change is to remove the topic from the `producer_options` and pass the topic upon sending the message, now with `send_msg` instead of `sendMsg`. Correct?

However, upon running this updated example, I run into the following error:

```
Encoder.scala:34:in `toBytes': java.lang.ClassCastException: java.lang.String cannot be cast to [B
	from kafka/serializer/Encoder.scala:34:in `toBytes'
	from DefaultEventHandler.scala:130:in `apply'
	from kafka/producer/async/DefaultEventHandler.scala:130:in `apply'
	from DefaultEventHandler.scala:125:in `apply'
	from kafka/producer/async/DefaultEventHandler.scala:125:in `apply'
	from IndexedSeqOptimized.scala:33:in `foreach'
	from scala/collection/IndexedSeqOptimized.scala:33:in `foreach'
	from WrappedArray.scala:34:in `foreach'
	from scala/collection/mutable/WrappedArray.scala:34:in `foreach'
	from DefaultEventHandler.scala:125:in `serialize'
	from kafka/producer/async/DefaultEventHandler.scala:125:in `serialize'
	from DefaultEventHandler.scala:52:in `handle'
	from kafka/producer/async/DefaultEventHandler.scala:52:in `handle'
	from Producer.scala:77:in `send'
	from kafka/producer/Producer.scala:77:in `send'
	from Producer.scala:33:in `send'
	from kafka/javaapi/producer/Producer.scala:33:in `send'
	from java/lang/reflect/Method.java:606:in `invoke'
	from org/jruby/RubyMethod.java:120:in `call'
	from /Users/aliekens/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/jruby-kafka-1.4.0-java/lib/jruby-kafka/producer.rb:70:in `send_msg'
	from producer.rb:7:in `(root)'
	from producer.rb:7:in `(root)'
```

What am I doing wrong?

**Comment by aliekens** [comment]
Apparently, the producer options should contain a serializer class to allow strings to be encoded to byte arrays, as follows:

```
producer_options = {:broker_list => "localhost:9092", "serializer.class" => "kafka.serializer.StringEncoder"}
```

I will submit a merge request with an updated example soon.
